### ISSUE TITLE
[syntax reference docs] node.type === 'Url' missing node.value.type === 'Raw'

### ISSUE THREAD

**Issue by UncleBill** [csstree/csstree#100]
screenshot from [https://astexplorer.net/]()

![image](https://user-images.githubusercontent.com/1141198/60852381-18ce2500-a22a-11e9-8887-65eeedefff6d.png)

```css
.div {
      background: url('//a.b.com.jpg'), url(//x.x.x/.jpg)
}
```

But there is only `type=String` in the docs. [https://csstree.github.io/docs/syntax/#Type:url]()
![image](https://user-images.githubusercontent.com/1141198/60852461-6480ce80-a22a-11e9-9e6a-9af6dd4bd560.png)
