### ISSUE TITLE
Add matching

### ISSUE THREAD

**Issue by strarsis** [csstree/csstree#127]
It would be very useful if `CSSTree` could offer a method for matching CSS selector against Selector and similar nodes.

**Comment by lahmatiy** [comment]
Not sure I get your idea. Can you explain a bit, an example maybe?

**Comment by strarsis** [comment]
@lahmatiy: Sure, so let's say I got CSS parsed into CSSTree:
```css
.test1 { color: red; }
.test2 { color: blue; }
.test3 { color: yellow; }
body.test { background: grey; }
````
Now I want to use the selector string `body.test` against each Selector node and find out what selector nodes match, in this case the Selector for last Rule node.
