### ISSUE TITLE
support range syntax from Media Queries Level 4

### ISSUE THREAD

**Issue by alexander-akait** [csstree/csstree#143]
Example:

```CSS
@media (height > 600px) {
    body { line-height: 1.4; }
}

@media (400px <= width <= 700px) {
    body { line-height: 1.4; }
}
```
