### ISSUE TITLE
Support :is() pseudo-class

### ISSUE THREAD

**Issue by valtlai** [csstree/csstree#151]
The CSS [`:is()` pseudo-class](https://drafts.csswg.org/selectors-4/#matches) is now [supported](https://caniuse.com/css-matches-pseudo) by the major browsers. It’s very much like `:matches()`, which CSSTree already supports.

For example,

```css
.nav-link:is(:hover, :active, :focus) {
   color: red;
}

/* equals */

.nav-link:hover,
.nav-link:active,
.nav-link:focus {
   color: red;
}
```
