### ISSUE TITLE
Add tolerance mode to parser

### ISSUE THREAD

**Issue by smelukov** [csstree/csstree#16]
``` css
.a {
  display: block;
}.
```

Gives

```
Parse error: Identifier is expected
    1 |.a{
    2 |  display: block;
    3 |}.
---------^
```

I expect that lexer will notify me about this error, but ignore it and continue to consume tokens
