### ISSUE TITLE
Valid use of calc in media queries results in an error

### ISSUE THREAD

**Issue by dumptyd** [csstree/csstree#162]
```css
@media (max-width: calc(400px + 1px)) {
  .btn { width: 100px; }
}
```
```diff
- Parse error: Number, dimension, ratio or identifier is expected
```

That code can be ran here to reproduce the error: https://csstree.github.io/docs/validator.html
