### ISSUE TITLE
css3 function max, min, toggle not support

### ISSUE THREAD

**Issue by kekee000** [csstree/csstree#164]
css function max, min, toggle not valid.

```css
.Foo {margin-top: max(10%, 7px);}
.Foo {margin-top: min(1em, 7px);}
.Foo {list-style-type: toggle(disk, circle, square, box);}
```

![image](https://user-images.githubusercontent.com/3490015/125444632-9a798a4e-e057-4fb0-ae96-ab0fee77d8e3.png)
