### ISSUE TITLE
Error character problems caused by pseudo-class content being escaped

### ISSUE THREAD

**Issue by Yorksh1re** [csstree/csstree#179]
Hello!

I found in my use that once the content of the pseudo-class has the '\\' symbol, it will be escaped to the wrong '' character, which is reproduced below.

```css
.iconfont:before {
  content: "\e600";
}
```

Then run:

```javascript
const cssAST = csstree.parse(css)
const finalCSS = csstree.generate(cssPlain)
```

In the generated CSS, the expected result is escaped and will look like this:

```css
.iconfont:before{content:""}
```

**Comment by thescientist13** [comment]
Just ran into this issue as well.  Here is a link to astexplorer.net that also reproduces the issue
https://astexplorer.net/#/gist/fe3f7886b4638ffc5bf66275c54d3af5/d503c4abef9da04298ffeccba4fdaef733e34858
![Screenshot 2024-07-20 at 7 30 51 PM](https://github.com/user-attachments/assets/e7ccd5f2-df2d-4923-9509-8a760094c36a)

**Comment by thescientist13** [comment]
Just bumped into this again while experimenting with FontAwesome, which makes pretty heavy use of this pattern
https://unpkg.com/browse/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.css
```css
.fa-circle-chevron-right::before {
  content: "\f138";
}
```
