### ISSUE TITLE
Support for mixed rules and declarations inside at-rules

### ISSUE THREAD

**Issue by kizu** [csstree/csstree#24]
Some CSS modules have mixed rules and declarations inside at-rules. An example: [Paged Media Module](https://drafts.csswg.org/css-page-3/) allowing stuff like this:

``` CSS
@page :first {
  color: green;

  @top-left {
    content: "foo";
    color: blue;
  }
  @top-right {
    content: "bar";
  }
}
```

Right now CSSTree returns `Parse error: Identifier is expected` error, while allowing either only declarations or only nested rules.

While this module is still in Editor's Draft, it is quite possible that other modules could allow this kind of syntax (and this could be helpful for external tools too of course).

**Comment by lahmatiy** [comment]
Thank you for issue!
Yep, just yesterday thought about the possibility of the rules within the block, and decided that it can be added to the parser, since there is a case in this module. Also this addition will allow to parse some non-standart (yet) things as side effect.
I'm going to implement it soon.

**Comment by lahmatiy** [comment]
CSS Syntax Module Level 3 CR says at-rule can be inside a declaration list:
https://www.w3.org/TR/css-syntax-3/#declaration-list-diagram

**Comment by kizu** [comment]
Also, could fall into this issue: `@apply` rule (https://tabatkins.github.io/specs/css-apply-rule/), already implemented under flag (https://www.chromestatus.com/feature/5753701012602880).

The syntax that should be supported for it:

``` CSS
foo {
  --bar: {
    width: 10px;
  };
}
```

While it is really experimental now and there is chance it would go away/be changed, if adding support for this is not really complicated, then it would be nice to have.
