### ISSUE TITLE
`oklch()` support

### ISSUE THREAD

**Issue by ai** [csstree/csstree#244]
This code

```css
.block {
  background: oklch(0% 0 0);
}
```

Throws an error in `declaration-property-value-no-unknown` rule in Stylelint 15:

```
Unexpected unknown value "oklch(" for property "background"
```

Seems like we need to add `oklch()` (and maybe other functions from CSS Color 4) to `csstree`.

`oklch()` is already working in Safari, upcoming Chrome 111 and Firefox Nightly.
