### ISSUE TITLE
`font-weight` descriptor in `@font-face` doesn't allow two values

### ISSUE THREAD

**Issue by FloEdelmann** [csstree/csstree#247]
For variable fonts, the `font-weight` descriptor of the `@font-face` at-rule accepts the minimum and maximum weights supported by the font:

```css
@font-face {
    font-family: 'AwesomeVariableFont';
    font-style: normal;
    font-weight: 100 700;
    src: url('./fonts/AwesomeVariableFont.woff2') format('woff2-variations');
}
```

In https://github.com/mdn/data/, this is reflected correctly: https://github.com/mdn/data/blob/678604eeb7cad0c1e5d637fa6918922be1b24be3/css/at-rules.json#L206-L214
However, CSSTree doesn't seem to use that (via https://csstree.github.io/docs/validator.html):

![grafik](https://user-images.githubusercontent.com/202916/219368591-aed3546d-791a-4458-9e88-b463cf7724d2.png)

See also:

* [MDN: `@font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#font-weight)
* [MDN: `@font-face`'s `font-weight` descriptor](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight) (compare also with [MDN: `font-weight` property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight))
* https://github.com/stylelint/stylelint/issues/6663
