### ISSUE TITLE
SyntaxError: ")" is expected

### ISSUE THREAD

**Issue by yoyo837** [csstree/csstree#254]
scss source:
```scss
@mixin iosSafeAreaBottom($offset: 0px) {
  bottom: $offset;
  bottom: calc(var(--body-padding-offset-bottom) + $offset); // this line
}
```

![image](https://user-images.githubusercontent.com/6134547/232372141-92c797bb-6987-43bf-a2c8-8995d42102fe.png)
