### ISSUE TITLE
Error [csstree-match] BREAK after 15000 iterations

### ISSUE THREAD

**Issue by PavelFil** [csstree/csstree#294]
This code:
```CSS
@media (hover:hover) and (pointer:fine) and (-ms-high-contrast:none),(hover:hover) and (pointer:fine) and screen and (-ms-high-contrast:active){
    .breadcrumbs .breadcrumbs__link:hover{
        border-color:#242424;
        color:#242424
    }
}
```
Return error:
```
[csstree-match] BREAK after 15000 iterations
```

**Comment by PavelFil** [comment]
Also this code catch the same issue:
```CSS
.range-block__range::-webkit-slider-thumb {
    box-shadow: 1px 0 0 -4px #cfcfcf, 2px 0 0 -5px #cfcfcf, 3px 0 0 -5px #cfcfcf, 4px 0 0 -5px #cfcfcf, 5px 0 0 -5px #cfcfcf, 6px 0 0 -5px #cfcfcf, 7px 0 0 -5px #cfcfcf, 8px 0 0 -5px #cfcfcf, 9px 0 0 -5px #cfcfcf, 10px 0 0 -5px #cfcfcf, 11px 0 0 -5px #cfcfcf, 12px 0 0 -5px #cfcfcf, 13px 0 0 -5px #cfcfcf, 14px 0 0 -5px #cfcfcf, 15px 0 0 -5px #cfcfcf, 16px 0 0 -5px #cfcfcf, 17px 0 0 -5px #cfcfcf, 18px 0 0 -5px #cfcfcf, 19px 0 0 -5px #cfcfcf, 20px 0 0 -5px #cfcfcf, 21px 0 0 -5px #cfcfcf, 22px 0 0 -5px #cfcfcf, 23px 0 0 -5px #cfcfcf, 24px 0 0 -5px #cfcfcf, 25px 0 0 -5px #cfcfcf, 26px 0 0 -5px #cfcfcf, 27px 0 0 -5px #cfcfcf, 28px 0 0 -5px #cfcfcf, 29px 0 0 -5px #cfcfcf, 30px 0 0 -5px #cfcfcf, 31px 0 0 -5px #cfcfcf, 32px 0 0 -5px #cfcfcf, 33px 0 0 -5px #cfcfcf, 34px 0 0 -5px #cfcfcf, 35px 0 0 -5px #cfcfcf, 36px 0 0 -5px #cfcfcf, 37px 0 0 -5px #cfcfcf, 38px 0 0 -5px #cfcfcf, 39px 0 0 -5px #cfcfcf, 40px 0 0 -5px #cfcfcf, 41px 0 0 -5px #cfcfcf, 42px 0 0 -5px #cfcfcf, 43px 0 0 -5px #cfcfcf, 44px 0 0 -5px #cfcfcf, 45px 0 0 -5px #cfcfcf, 46px 0 0 -5px #cfcfcf, 47px 0 0 -5px #cfcfcf, 48px 0 0 -5px #cfcfcf, 49px 0 0 -5px #cfcfcf, 50px 0 0 -5px #cfcfcf, 51px 0 0 -5px #cfcfcf, 52px 0 0 -5px #cfcfcf, 53px 0 0 -5px #cfcfcf, 54px 0 0 -5px #cfcfcf, 55px 0 0 -5px #cfcfcf, 56px 0 0 -5px #cfcfcf, 57px 0 0 -5px #cfcfcf, 58px 0 0 -5px #cfcfcf, 59px 0 0 -5px #cfcfcf, 60px 0 0 -5px #cfcfcf, 61px 0 0 -5px #cfcfcf, 62px 0 0 -5px #cfcfcf, 63px 0 0 -5px #cfcfcf, 64px 0 0 -5px #cfcfcf, 65px 0 0 -5px #cfcfcf, 66px 0 0 -5px #cfcfcf, 67px 0 0 -5px #cfcfcf, 68px 0 0 -5px #cfcfcf, 69px 0 0 -5px #cfcfcf, 70px 0 0 -5px #cfcfcf, 71px 0 0 -5px #cfcfcf, 72px 0 0 -5px #cfcfcf, 73px 0 0 -5px #cfcfcf, 74px 0 0 -5px #cfcfcf, 75px 0 0 -5px #cfcfcf, 76px 0 0 -5px #cfcfcf, 77px 0 0 -5px #cfcfcf, 78px 0 0 -5px #cfcfcf, 79px 0 0 -5px #cfcfcf, 80px 0 0 -5px #cfcfcf, 81px 0 0 -5px #cfcfcf, 82px 0 0 -5px #cfcfcf, 83px 0 0 -5px #cfcfcf, 84px 0 0 -5px #cfcfcf, 85px 0 0 -5px #cfcfcf, 86px 0 0 -5px #cfcfcf, 87px 0 0 -5px #cfcfcf, 88px 0 0 -5px #cfcfcf, 89px 0 0 -5px #cfcfcf, 90px 0 0 -5px #cfcfcf, 91px 0 0 -5px #cfcfcf, 92px 0 0 -5px #cfcfcf, 93px 0 0 -5px #cfcfcf, 94px 0 0 -5px #cfcfcf, 95px 0 0 -5px #cfcfcf, 96px 0 0 -5px #cfcfcf, 97px 0 0 -5px #cfcfcf, 98px 0 0 -5px #cfcfcf, 99px 0 0 -5px #cfcfcf, 100px 0 0 -5px #cfcfcf, 101px 0 0 -5px #cfcfcf, 102px 0 0 -5px #cfcfcf, 103px 0 0 -5px #cfcfcf, 104px 0 0 -5px #cfcfcf, 105px 0 0 -5px #cfcfcf, 106px 0 0 -5px #cfcfcf, 107px 0 0 -5px #cfcfcf, 108px 0 0 -5px #cfcfcf, 109px 0 0 -5px #cfcfcf, 110px 0 0 -5px #cfcfcf, 111px 0 0 -5px #cfcfcf, 112px 0 0 -5px #cfcfcf, 113px 0 0 -5px #cfcfcf, 114px 0 0 -5px #cfcfcf, 115px 0 0 -5px #cfcfcf, 116px 0 0 -5px #cfcfcf, 117px 0 0 -5px #cfcfcf, 118px 0 0 -5px #cfcfcf, 119px 0 0 -5px #cfcfcf, 120px 0 0 -5px #cfcfcf, 121px 0 0 -5px #cfcfcf, 122px 0 0 -5px #cfcfcf, 123px 0 0 -5px #cfcfcf, 124px 0 0 -5px #cfcfcf, 125px 0 0 -5px #cfcfcf, 126px 0 0 -5px #cfcfcf, 127px 0 0 -5px #cfcfcf, 128px 0 0 -5px #cfcfcf, 129px 0 0 -5px #cfcfcf, 130px 0 0 -5px #cfcfcf, 131px 0 0 -5px #cfcfcf, 132px 0 0 -5px #cfcfcf, 133px 0 0 -5px #cfcfcf, 134px 0 0 -5px #cfcfcf, 135px 0 0 -5px #cfcfcf, 136px 0 0 -5px #cfcfcf, 137px 0 0 -5px #cfcfcf, 138px 0 0 -5px #cfcfcf, 139px 0 0 -5px #cfcfcf, 140px 0 0 -5px #cfcfcf, 141px 0 0 -5px #cfcfcf, 142px 0 0 -5px #cfcfcf, 143px 0 0 -5px #cfcfcf, 144px 0 0 -5px #cfcfcf, 145px 0 0 -5px #cfcfcf, 146px 0 0 -5px #cfcfcf, 147px 0 0 -5px #cfcfcf, 148px 0 0 -5px #cfcfcf, 149px 0 0 -5px #cfcfcf, 150px 0 0 -5px #cfcfcf, 151px 0 0 -5px #cfcfcf, 152px 0 0 -5px #cfcfcf, 153px 0 0 -5px #cfcfcf, 154px 0 0 -5px #cfcfcf, 155px 0 0 -5px #cfcfcf, 156px 0 0 -5px #cfcfcf, 157px 0 0 -5px #cfcfcf, 158px 0 0 -5px #cfcfcf, 159px 0 0 -5px #cfcfcf, 160px 0 0 -5px #cfcfcf, 161px 0 0 -5px #cfcfcf, 162px 0 0 -5px #cfcfcf, 163px 0 0 -5px #cfcfcf, 164px 0 0 -5px #cfcfcf, 165px 0 0 -5px #cfcfcf, 166px 0 0 -5px #cfcfcf, 167px 0 0 -5px #cfcfcf, 168px 0 0 -5px #cfcfcf, 169px 0 0 -5px #cfcfcf, 170px 0 0 -5px #cfcfcf, 171px 0 0 -5px #cfcfcf, 172px 0 0 -5px #cfcfcf, 173px 0 0 -5px #cfcfcf, 174px 0 0 -5px #cfcfcf, 175px 0 0 -5px #cfcfcf, 176px 0 0 -5px #cfcfcf, 177px 0 0 -5px #cfcfcf, 178px 0 0 -5px #cfcfcf, 179px 0 0 -5px #cfcfcf, 180px 0 0 -5px #cfcfcf, 181px 0 0 -5px #cfcfcf, 182px 0 0 -5px #cfcfcf, 183px 0 0 -5px #cfcfcf, 184px 0 0 -5px #cfcfcf, 185px 0 0 -5px #cfcfcf, 186px 0 0 -5px #cfcfcf, 187px 0 0 -5px #cfcfcf, 188px 0 0 -5px #cfcfcf, 189px 0 0 -5px #cfcfcf, 190px 0 0 -5px #cfcfcf, 191px 0 0 -5px #cfcfcf, 192px 0 0 -5px #cfcfcf, 193px 0 0 -5px #cfcfcf, 194px 0 0 -5px #cfcfcf, 195px 0 0 -5px #cfcfcf, 196px 0 0 -5px #cfcfcf, 197px 0 0 -5px #cfcfcf, 198px 0 0 -5px #cfcfcf, 199px 0 0 -5px #cfcfcf, 200px 0 0 -5px #cfcfcf;
}
```
