### ISSUE TITLE
Validaton CSS variables name 

### ISSUE THREAD

**Issue by PavelFil** [csstree/csstree#298]
Hello. This code doesn't show any error.
```CSS
body {
    color: var(primary-color);
}
```
But property names must be prefixed with --.

https://github.com/csstree/validator/issues/38
