### ISSUE TITLE
Unknown custom properties inside @media

### ISSUE THREAD

**Issue by pepelsbey** [csstree/csstree#31]
In the following file `--list-scale` property is marked as unknown though it works fine in browsers:

```css
.shower.list {

    position: absolute;
    clip: rect(0 auto auto 0);

    margin: 0;
    padding-top: calc(
        var(--slide-width) *
        var(--list-gutter) *
        var(--list-scale));
    padding-left: calc(
        var(--slide-width) *
        var(--list-gutter) *
        var(--list-scale));

    display: flex;
    flex-wrap: wrap;

    background: #666;

    }

/* Scale */

@media (min-width: 1120px) {
    .shower.list {
        --list-scale: 0.5;
        }
    }
@media (min-width: 2240px) {
    .shower.list {
        --list-scale: 1;
        }
    }
```

![image](https://cloud.githubusercontent.com/assets/105274/22113984/0f51a4ba-de79-11e6-962f-13974a56b0c6.png)
