### ISSUE TITLE
Cannot handle `number` in hsl component

### ISSUE THREAD

**Issue by Chocobo1** [csstree/csstree#316]
The validator at https://csstree.github.io/docs/validator.html deem the following css as invalid:
```css
#x {
    color: hsl(0deg 0 0 / 30%);
}
```
However, it should be valid css. According to https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl#formal_syntax, the `S` and `L` can be `[ <percentage> | <number> | none ]`.

If I change the css to:
```css
#x {
    color: hsl(0deg 0% 0% / 30%);
}
```
Then the validator says it is valid. It seems that the validator didn't know about `<number>` or refuse to accept it.
