### ISSUE TITLE
overflow: -moz-scrollbars-none is marked as invalid by CSS syntax validator

### ISSUE THREAD

**Issue by victor-homyakov** [csstree/csstree#76]
[CSS syntax validator](https://csstree.github.io/docs/validator.html) marks `overflow: -moz-scrollbars-none` declaration as invalid

Firefox 57 suggests also `-moz-hidden-unscrollable` as acceptable value

https://csstree.github.io/docs/syntax.html#Property:overflow allows only `visible | hidden | scroll | auto`

**Comment by victor-homyakov** [comment]
Questions like "hide scrollbars in Firefox" are very popular on Stack Overflow. Carousel is a practical example where we may want to hide scrollbars:

```css
.carousel-wrap {
    -ms-overflow-style: none;
}

.carousel-wrap {
    overflow: -moz-scrollbars-none;
}

.carousel-wrap::-webkit-scrollbar {
    display: none;
}
```

Here we are hiding scrollbars while keeping carousel scrollable in most of the browsers. The simplest solution for Firefox is the CSS-only with vendor prefix (while losing the ability of scrolling). Other solutions, like user agent sniffing or detecting scrollbar visibility at runtime, are more complex.

In any case, this value shouldn't be marked as invalid by CSS validator (maybe it could be marked as deprecated).
