### ISSUE TITLE
Unmatched " character terminating declaration causes following rules to be swallowed

### ISSUE THREAD

**Issue by pocketjoso** [csstree/csstree#93]
Hi @lahmatiy, how are you doing? Thanks again for this great library.

I just came across a case where csstree never recovers after a syntax errors, whereas browsers do. Ideally for me csstree could handle this - but not sure how easy it would be for you to handle.

## Reduced test case
```css

.first {
  color: red"
}
.thisAndAllFollowingRulesGetSwallowed {
  color: red
}
```
You can see this in effect in the [astexplorer](https://astexplorer.net/#/gist/aaf18a12efd85c47481e06638f79f404/d07ccbd311e549898715dc290966c994771e0756).

## expectation
The AST parsing recovers, and correctly parses rules following the broken `.first` one.

Cheers,
Jonas
